### ISSUE TITLE
Script exited at xcode-tools install even though it continued installing

### ISSUE THREAD

**Issue by nunofgs** [uphold/strap#4]
<img width="1148" alt="screenshot 2018-11-13 at 21 43 54" src="https://user-images.githubusercontent.com/92085/49521533-8d5c7200-f89d-11e8-990b-d8236411b69d.png">

**Comment by ricardobcl** [comment]
Seems like `xcode-select --install` starts the update and the script does not wait for it to be complete.
This was most likely fixed in [PR 7](https://github.com/uphold/strap/pull/7), where the old mechanism for installing the CLT was restored.
